In [1]:
import numpy as np

## Indexação de arrays unidimensionais

In [2]:
exemplo = np.random.randint(20, 60, 10)
exemplo

array([58, 26, 37, 30, 22, 20, 28, 30, 25, 59])

### Pegando um elemento:

In [3]:
# Se eu quiser o elemento que se encontra no índice 3 desse único array (vetor)
# Lembre-se que a indexação começa por 0
exemplo[3]

30

### exemplo[3]
- exemplo = nome do array
- [3] = índice onde se encontra o elemento que se quer

### Pegando mais de um elemento:
- Segue-se as regras de slice de listas, strings, ...

In [4]:
dois_elementos = exemplo[4:6]  # Vamos pegar os elementos no intervalo de 4 a 6(este não incluso)
print(dois_elementos)          # Assim os elementos pegos serão os de índice 4 e 5

[22 20]


### exemplo[4:6]
- exemplo = nome do array
- 4 = índice de início do slice (é incluído)
- 6 = índice do final do slice (não é incluído)bb

## Indexação de arrays com mais de uma dimensão

### Observe a Matriz abaixo:

In [5]:
linha_coluna = np.array([['00','01', '02'], ['10', '11', '12'], ['20', '21', '22']])
linha_coluna

array([['00', '01', '02'],
       ['10', '11', '12'],
       ['20', '21', '22']], dtype='<U2')

### Os elementos da matriz representam suas linhas e colunas:
- [linha, coluna]
- linhas a esquerda = 00 -> linha zero, coluna 0 ;  
- colunas a direita = 12 -> linha 1, coluna 2


### Exemplos de indexação de arrays com mais de uma dimenção:

In [6]:
matriz = np.random.randint(1, 15, size=(4,4))
matriz

array([[ 9,  2,  9, 10],
       [ 5, 14,  3, 11],
       [ 6,  3,  8,  4],
       [ 7,  3,  9,  7]])

### Vamos pegar o elemento da linha 2 e coluna 1
- lembre-se que a indexação em python começa com 0.

In [7]:
matriz[2][1]

3

### Vamos pegar as três primeiras linhas:

In [29]:
matriz[:][0:3] 

array([[ 9,  2,  9, 10],
       [ 5, 14,  3, 11],
       [ 6,  3,  8,  4]])

### matriz[:][:3]
- matriz = nome da Matriz
- [:] = todo conteúdo da linha
- [:3] = pegamos as colunas 0, 1 e 2

In [9]:
matriz[0:3, 0:4]

array([[ 9,  2,  9, 10],
       [ 5, 14,  3, 11],
       [ 6,  3,  8,  4]])

In [30]:
matriz[0:3][2:3]

array([[6, 3, 8, 4]])

In [11]:
matriz[2:3, 0:4] # pega somente a linha 2 e todos o seu conteúdo.

array([[6, 3, 8, 4]])

In [62]:
nova_matriz = np.array([[88, 19, 46, 74, 94], [69, 79, 26, 7, 29], [21, 45, 12, 80, 72],
                       [28, 53, 65, 26, 64], [71, 96, 34, 61, 52]])
nova_matriz

array([[88, 19, 46, 74, 94],
       [69, 79, 26,  7, 29],
       [21, 45, 12, 80, 72],
       [28, 53, 65, 26, 64],
       [71, 96, 34, 61, 52]])

### Vamos pegar os elementos sequenciais: 79, 26, 7


In [35]:
nova_matriz[1:2, 1:4]  # [1:2 ,...] Elementos da linha 1 até a 2(não incluso), então somente a linha 1
                       # [..., 1:4] Elementos da coluna 1 até a 4 (não incluso), então somente até a coluna 3.

array([[79, 26,  7]])

### Vamos pegar a mesma sequência com outra notação:    

In [96]:
nova_matriz[1:2][:]

array([[69, 79, 26,  7, 29]])

Vamos pegar os seguintes elementos:
 - 79, 26, 7
 - 45, 12, 80

In [37]:
nova_matriz[1:3, 1:4]

array([[79, 26,  7],
       [45, 12, 80]])

### Vamos pegar a quarta coluna ( em pytho seria a coluna 03)

In [31]:
matriz[0:,3:4]
# note que mudamos a notação!
# assim eu consigo capturar as colunas desejadas.

array([[10],
       [11],
       [ 4],
       [ 7]])

### Repare que o array anterior é composto da terceira coluna  da Matriz

In [13]:
# Vamos pegar a primeira e segunda colunas:
matriz[:, 1:3]


array([[ 2,  9],
       [14,  3],
       [ 3,  8],
       [ 3,  9]])

### Vamos capturar linhas não sequenciais da Matriz:

In [14]:
matriz_1 = np.random.randint(1, 15, size=(6,4))

In [15]:
matriz_1

array([[ 3,  6, 10,  5],
       [ 7,  7,  3,  8],
       [12,  6,  1,  2],
       [12,  6,  4,  7],
       [10, 12, 12,  3],
       [14,  1,  1,  4]])

### Vamos pegar as linhas 0, 3 e 5:

In [16]:
matriz_1[[0, 3, 5]]

array([[ 3,  6, 10,  5],
       [12,  6,  4,  7],
       [14,  1,  1,  4]])

### Pode ser em ordem aleatória.

In [17]:
matriz_1[[5, 0, 2]]

array([[14,  1,  1,  4],
       [ 3,  6, 10,  5],
       [12,  6,  1,  2]])

In [18]:
matriz_1[:, 0:2]

array([[ 3,  6],
       [ 7,  7],
       [12,  6],
       [12,  6],
       [10, 12],
       [14,  1]])

In [19]:
capturando_sequencias = np.array([[ 1, 11, 18,  8, 34],
                                  [ 8,  3, 31,  1,  6],
                                  [29, 12,  3, 39,  4],
                                  [11, 25,  6,  1, 36],
                                  [15, 12, 32,  8, 31]])
capturando_sequencias

array([[ 1, 11, 18,  8, 34],
       [ 8,  3, 31,  1,  6],
       [29, 12,  3, 39,  4],
       [11, 25,  6,  1, 36],
       [15, 12, 32,  8, 31]])

### Vamos pegar a seguinte sequência:
 - 12, 3, 39 ==> linha 3  da matriz (em python linha 2) e colunas 2, 3 e 4 (em python 1, 2 e 3)
 - 25, 6, 1  ==> linha 4  da matriz (em python linha 3) e colunas 2, 3 e 4 (em python 1, 2 e 3)

In [20]:
capturando_sequencias[2:4,1:4]

array([[12,  3, 39],
       [25,  6,  1]])

## Capturando valores em uma matriz por uma determinada condição

### Vamos supor que uma certa quantidade de crianças, em um parque, querem entrar em um brinquedo.
 - para entrar no brinquedo, tem que ter a altura a partir de 120cm
 - a matriz é composta das alturas das crianças

### Trivial

In [21]:
altura_criancas = np.array([[132, 126, 121,  98,  90,  91],
                            [100, 134, 105, 107, 110, 106],
                            [133,  94, 131, 127, 120, 110],
                            [111,  98, 116, 130, 102, 117],
                            [105, 119, 136,  99, 107, 102],
                            [ 99, 102, 134, 133, 108, 116]])
altura_criancas

array([[132, 126, 121,  98,  90,  91],
       [100, 134, 105, 107, 110, 106],
       [133,  94, 131, 127, 120, 110],
       [111,  98, 116, 130, 102, 117],
       [105, 119, 136,  99, 107, 102],
       [ 99, 102, 134, 133, 108, 116]])

In [22]:
# Vamos colocar a condição para a seleção:
entrada_permitida = altura_criancas > 119 
entrada_permitida

array([[ True,  True,  True, False, False, False],
       [False,  True, False, False, False, False],
       [ True, False,  True,  True,  True, False],
       [False, False, False,  True, False, False],
       [False, False,  True, False, False, False],
       [False, False,  True,  True, False, False]])

In [23]:
# Vamos expor as alturas que atendem a condição:
altura_criancas[entrada_permitida]

array([132, 126, 121, 134, 133, 131, 127, 120, 130, 136, 134, 133])

### Otimizando

In [24]:
altura_criancas[altura_criancas>119]

array([132, 126, 121, 134, 133, 131, 127, 120, 130, 136, 134, 133])

### Outra maneira
 - Usando a função extract do Numpy

In [25]:
condicao_exigida = altura_criancas>119

In [26]:
condicao_atendida = np.extract(condicao_exigida, altura_criancas)
condicao_atendida

array([132, 126, 121, 134, 133, 131, 127, 120, 130, 136, 134, 133])