# O que é Numpy

###  Numpy é um pacote para computação científica usado em Python, que fornece recursos e uma variedade de rotinas para operações rápidas em matrizes, incluindo matemática, lógica, manipulação de formas, classificação, seleção, E/S (I/O), transformações discretas de Fourier, álgebra linear básica, operações estatísticas básicas, simulação aleatória e muito mais.


## Criação de um Array:

### 1) A biblioteca Numpy não é nativa, logo temos que importá-la;
### 2) É comum na comunidade Python você dá um elias para a biblioteca, usaremos a padrão "np";
### 3) Guardamos o Array em uma variável.

In [ ]:
import numpy as np

## Criando um Array unidimensional 

In [2]:
a = np.array([1, 2, 3])

In [3]:
# observemos o tipo do objeto criado
print(type(a)) 
print(a)

<class 'numpy.ndarray'>
[1 2 3]


## Criando um Array com mais de uma dimensão 

In [4]:
b = np.array([[1, 2, 3], [1, 4, 9]])

In [5]:
print(b)

[[1 2 3]
 [1 4 9]]


# Os atributos mais importantes de um objeto array são:

## ndarray.ndim
 - Nos dá o número de eixos (dimensões) da matriz.
 
## ndarray.shape
- Dá as dimensões da matriz. Esta é uma tupla de inteiros indicando o tamanho da matriz em cada dimensão. Para
  matriz com n linhas em colunas, a forma será (n, m). O comprimento da tupla de forma é, portanto, o número
  de dimensões, ndim.
  
## ndarray.size
 - nos dá o número total de elementos da matriz. 
 
## ndarray.dtype
 - um objeto que descreve o tipo dos elementos na matriz. Pode-se criar ou especificar dtype's usando o tipo padrão do Python.    Além disso, o NumPy fornece seus próprios tipos. (numpy.int32, numpy.int16 e numpy.float64) são alguns exemplos.
 
## ndarray.itemsize
 - Nos dá o tamanho em bytes de cada elemento da matriz. Por exemplo, uma matriz de elementos do tipo float64 tem itemsize
   8 (= 64/8), enquanto um do tipo complex32 tem tamanho de item 4 (= 32/8). 
   
## ndarray.data
 - Nos dá o buffer que contém os elementos reais da matriz. Normalmente, não precisamos usar este atributo porque nós podemos 
   acessará os elementos em uma matriz usando recursos de indexação.