# O que é Numpy

###  Numpy é um pacote para computação científica usado em Python, que fornece recursos e uma variedade de rotinas para operações rápidas em matrizes, incluindo matemática, lógica, manipulação de formas, classificação, seleção, E/S (I/O), transformações discretas de Fourier, álgebra linear básica, operações estatísticas básicas, simulação aleatória e muito mais.


## Criação de um Array:

### 1) A biblioteca Numpy não é nativa, logo temos que importá-la;
### 2) É comum na comunidade Python você dá um elias para a biblioteca, usaremos a padrão "np";
### 3) Guardamos o Array em uma variável.

In [1]:
import numpy as np

## Criando um Array unidimensional 

In [2]:
a = np.array([1, 2, 3])

In [3]:
# observemos o tipo do objeto criado
print(type(a)) 
print(a)

<class 'numpy.ndarray'>
[1 2 3]


## Criando um Array com a função ( arange() )
- A função arange cria um arranjo contendo uma seqüência de valores especificados em um intervalo com início e fim dados, espaçados de maneira uniforme.

### np.arange(2, 15, 3, dtype=float)
- 2 = ponto de partida
- 15 = ponto de parada
- 3 = incremento
- dtype=float = tpipo de dado

In [4]:
np.arange(1, 10, 2, dtype=float)

array([1., 3., 5., 7., 9.])

## Criando um Array com o método ( linspace() )
-  A função linspace cria uma seqüência de números uniformemente espaçados entre os limites dados.

### np.linspace(1.0, 10.0, num = 5, dtype=float)
- 1.0 = ponto de partida
- 10.0 = ponto de parada
- 5 = quantidade de valores
- dtype=float = tipo de dado

In [5]:
np.linspace(1, 10, num=7, dtype=float)

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

### Se não for informado a quantidade de valores serão criados, por padrão, 50 valores.

In [6]:
np.linspace(1, 10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

## Criando um Array com:
### rand
- Cria um array com distribuição uniforme de números aleatórios entre 0 e 1.
 - np.random.rand(10)
   - 10 = número de valores.
   
### randn
- Cria um array de distribuição normal, de média 0 e variância 1.
 - np.random.randn(10)
   - 10 = número de valores.


### randint
- Cria um array com o número determinado de valores inteiros, aleatórios em um intervalo estabelecido. 
 - np.random.randint(5, 20, 12)
   - 5 = início 
   - 20 = final 
   - 12 = quantidade de valores

## Entendendo a chamada da função:
### np.random.rand()
- np = Biblioteca "Numpy"
- random = Módulo "random", contido na Biblioteca "Nunpy"
- rand = Função "rand", contida no Módulo "random"

In [7]:
np.random.rand(23)      

array([0.67742547, 0.38859771, 0.61412215, 0.25839478, 0.8509959 ,
       0.85645127, 0.82377557, 0.15868741, 0.22602614, 0.98833179,
       0.96267764, 0.71137825, 0.32455621, 0.38095225, 0.13818565,
       0.39197979, 0.96816732, 0.34146237, 0.99377026, 0.38763719,
       0.76684335, 0.33414103, 0.04438467])

In [8]:
np.random.randn(12)

array([ 0.08263333, -0.49727469, -0.50390052,  0.59726812,  1.72453442,
       -0.37518548, -0.59354182, -1.11485415,  0.50561546, -0.25203159,
        0.90719584, -0.57666833])

In [9]:
np.random.randint(3, 27, 10)

array([ 3, 17, 17,  5, 19,  6, 16, 21,  9, 13])

### se você limitar muito o intervalo, ele repete valores, como abaixo:

In [10]:
np.random.randint(3, 4, 6)

array([3, 3, 3, 3, 3, 3])

# Os atributos mais importantes de um objeto array são:

## ndarray.ndim
 - Nos dá o número de eixos (dimensões) da matriz.
 
## ndarray.shape
- Dá as dimensões da matriz. Esta é uma tupla de inteiros indicando o tamanho da matriz em cada dimensão. Para
  matriz com n linhas em colunas, a forma será (n, m). O comprimento da tupla de forma é, portanto, o número
  de dimensões, ndim.
  
## ndarray.size
 - nos dá o número total de elementos da matriz. 
 
## ndarray.dtype
 - um objeto que descreve o tipo dos elementos na matriz. Pode-se criar ou especificar dtype's usando o tipo padrão do Python.    Além disso, o NumPy fornece seus próprios tipos. (numpy.int32, numpy.int16 e numpy.float64) são alguns exemplos.
 
## ndarray.itemsize
 - Nos dá o tamanho em bytes de cada elemento da matriz. Por exemplo, uma matriz de elementos do tipo float64 tem itemsize
   8 (= 64/8), enquanto um do tipo complex32 tem tamanho de item 4 (= 32/8). 
   
## ndarray.data
 - Nos dá o buffer que contém os elementos reais da matriz. Normalmente, não precisamos usar este atributo porque nós podemos 
   acessará os elementos em uma matriz usando recursos de indexação.

In [11]:
# Dado o Array:
vetor = np.array([1, 2, 3, 4, 5, 6, 7, 9])

In [12]:
print(f'Meu número de eixos é: {vetor.ndim}')
print(f'Meu número de dimensões é: {vetor.shape}')
print(f'Meu número de elementos é: {vetor.size}')
print(f'Eu possuo o seguinte tipo de dados: {vetor.dtype}')
print(f'O tamanho em bytes de cada elemento vetor é: {vetor.itemsize}')
print(f'O buffer que contém os elementos reais da matriz é: {vetor.data}')




Meu número de eixos é: 1
Meu número de dimensões é: (8,)
Meu número de elementos é: 8
Eu possuo o seguinte tipo de dados: int32
O tamanho em bytes de cada elemento vetor é: 4
O buffer que contém os elementos reais da matriz é: <memory at 0x000002B67EF8E408>


## Criação de algumas matrizes especiais:
### Matriz com todos os elementos contendo "0"
### Matriz com todos os elementos contendo "1"
### Matriz Identidade
### Matriz diagonal

In [13]:
matriz_0 = np.zeros((4, 5))
print(matriz_0)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
matriz_1 = np.ones((4, 5))
print(matriz_1)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [15]:
matriz_identidade = np.eye(4)
print(matriz_identidade)
# Sempre uma madriz quadrada


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
matriz_diag = np.diag([4, 5, 1, 6])
print(matriz_diag)
# Sempre uma madriz quadrada, a dimensão vai depender da quantidade de elementos da diagonal passada.

[[4 0 0 0]
 [0 5 0 0]
 [0 0 1 0]
 [0 0 0 6]]


# Criando um Array com mais de uma dimensão 

In [17]:
b = np.array([[1, 2, 3], [1, 4, 9]])

In [18]:
print(b)

[[1 2 3]
 [1 4 9]]


In [19]:
# Note que a quantidade de "colchetes" que inicializa e finaliza o Array, mostram quantas dimensões ele possui.

# Indexação de arrays

## Indexação de arrays unidimensionais

In [20]:
exemplo = np.random.randint(20, 60, 10)
exemplo

array([34, 32, 32, 58, 34, 58, 40, 50, 28, 55])

### Pegando um elemento:

In [21]:
# Se eu quiser o elemento que se encontra no índice 3
# Lembre-se que a indexação começa por 0
exemplo[3]

58

### exemplo[3]
- exemplo = nome do array
- [3] = índice onde se encontra o elemento que se quer

### Pegando mais de um elemento:
- Segue-se as regras de slice de listas, strings, ...

In [22]:
dois_elementos = exemplo[4:6]
print(dois_elementos)

[34 58]


### exemplo[4:6]
- exemplo = nome do array
- 4 = índice de início do slice (é incluído)
- 6 = índice do final do slice (não é incluído)bb

## Indexação de arrays com mais de uma dimensão

### Observe a Matriz abaixo:

In [23]:
linha_coluna = np.array([['00','01', '02'], ['10', '11', '12'], ['20', '21', '22']])
linha_coluna

array([['00', '01', '02'],
       ['10', '11', '12'],
       ['20', '21', '22']], dtype='<U2')

### Os elementos da matriz representam suas linhas e colunas:
- linhas a esquerda = 00 -> linha zero, coluna 0 ; 12 -> linha 1, coluna 2
- colunas a direita = 12 -> linha 1, coluna 2

### Exemplos de indexação de arrays com mais de uma dimenção:

In [24]:
matriz = np.random.randint(1, 15, size=(4,4))
matriz

array([[ 1,  5,  6,  4],
       [12, 11,  1, 14],
       [12,  6, 14, 13],
       [13, 11, 11, 12]])

### Vamos pegar o elemento da linha 2 e coluna 1
- lembre-se que a indexação em python começa com 0.

In [25]:
matriz[2][1]

6

### Vamos pegar as três primeiras linhas:

In [26]:
matriz[:][:3]

array([[ 1,  5,  6,  4],
       [12, 11,  1, 14],
       [12,  6, 14, 13]])

### matriz[:][:3]
- matriz = nome da Matriz
- [:] = todo conteúdo da linha
- [:3] = pegamos as colunas 0, 1 e 2

In [27]:
matriz[0:3][2:3]

array([[12,  6, 14, 13]])

### Vamos pegar a terceira coluna ( em pytho seria a coluna 02)

In [30]:
matriz[0:,0:1]
# note que mudamos a notação!
# assim eu consigo capturar as colunas desejadas.

array([[ 1],
       [12],
       [12],
       [13]])

### Repare que o array anterior é composto da primeira coluta  da Matriz

In [29]:
# Vamos pegar a primeira e segunda colunas:
matriz[:, 1:3]


array([[ 5,  6],
       [11,  1],
       [ 6, 14],
       [11, 11]])

### Vamos capturar linhas não sequenciais da Matriz:

In [50]:
matriz_1 = np.random.randint(1, 15, size=(6,4))

In [51]:
matriz_1

array([[14, 11,  4, 10],
       [ 9,  5,  8, 13],
       [12,  4,  6,  4],
       [ 4, 13, 10,  6],
       [ 9,  6, 13, 10],
       [10, 13, 12, 12]])

### Vamos pegar as linhas 0, 3 e 5:

In [53]:
matriz_1[[0, 3, 5]]

array([[14, 11,  4, 10],
       [ 4, 13, 10,  6],
       [10, 13, 12, 12]])

### Pode ser em ordem aleatória.

In [55]:
matriz_1[[5, 0, 2]]

array([[10, 13, 12, 12],
       [14, 11,  4, 10],
       [12,  4,  6,  4]])

In [59]:
matriz_1[:, 0:2]

array([[14, 11],
       [ 9,  5],
       [12,  4],
       [ 4, 13],
       [ 9,  6],
       [10, 13]])