# O que é Numpy

###  Numpy é um pacote para computação científica usado em Python, que fornece recursos e uma variedade de rotinas para operações rápidas em matrizes, incluindo matemática, lógica, manipulação de formas, classificação, seleção, E/S (I/O), transformações discretas de Fourier, álgebra linear básica, operações estatísticas básicas, simulação aleatória e muito mais.


## Criação de um Array:

### 1) A biblioteca Numpy não é nativa, logo temos que importá-la;
### 2) É comum na comunidade Python você dá um elias para a biblioteca, usaremos a padrão "np";
### 3) Guardamos o Array em uma variável.

In [ ]:
import numpy as np

## Criando um Array unidimensional 

In [2]:
a = np.array([1, 2, 3])

In [3]:
# observemos o tipo do objeto criado
print(type(a)) 
print(a)

<class 'numpy.ndarray'>
[1 2 3]


## Criando um Array com mais de uma dimensão 

In [4]:
b = np.array([[1, 2, 3], [1, 4, 9]])

In [5]:
print(b)

[[1 2 3]
 [1 4 9]]
