# O que é Numpy

###  Numpy é um pacote para computação científica usado em Python, que fornece recursos e uma variedade de rotinas para operações rápidas em matrizes, incluindo matemática, lógica, manipulação de formas, classificação, seleção, E/S (I/O), transformações discretas de Fourier, álgebra linear básica, operações estatísticas básicas, simulação aleatória e muito mais.


## Criação de um Array:

### 1) A biblioteca Numpy não é nativa, logo temos que importá-la;
### 2) É comum na comunidade Python você dá um elias para a biblioteca, usaremos a padrão "np";
### 3) Guardamos o Array em uma variável.

In [26]:
import numpy as np

## Criando um Array unidimensional 

In [27]:
a = np.array([1, 2, 3])

In [28]:
# observemos o tipo do objeto criado
print(type(a)) 
print(a)

<class 'numpy.ndarray'>
[1 2 3]


## Criando um Array com a função ( arange() )
- A função arange cria um arranjo contendo uma seqüência de valores especificados em um intervalo com início e fim dados, espaçados de maneira uniforme.

### np.arange(2, 15, 3, dtype=float)
- 2 = ponto de partida
- 15 = ponto de parada
- 3 = incremento
- dtype=float = tpipo de dado

In [29]:
np.arange(1, 10, 2, dtype=float)

array([1., 3., 5., 7., 9.])

## Criando um Array com o método ( linspace() )
-  A função linspace cria uma seqüência de números uniformemente espaçados entre os limites dados.

### np.linspace(1.0, 10.0, num = 5, dtype=float)
- 1.0 = ponto de partida
- 10.0 = ponto de parada
- 5 = quantidade de valores
- dtype=float = tipo de dado

In [30]:
np.linspace(1, 10, num=7, dtype=float)

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

## Criando um Array com:
### rand
- Cria um array com distribuição uniforme de números aleatórios entre 0 e 1.
 - np.random.rand(10)
   - 10 = número de valores.
   
### randn
- Cria um array de distribuição normal, de média 0 e variância 1.
 - np.random.randn(10)
   - 10 = número de valores.


### randint
- Cria um array com o número determinado de valores inteiros, aleatórios em um intervalo estabelecido. 
 - np.random.randint(5, 20, 12)
   - 5 = início 
   - 20 = final 
   - 12 = quantidade de valores

In [31]:
np.random.rand(23)      

array([0.78415363, 0.5104413 , 0.53310103, 0.15362388, 0.56146349,
       0.99410719, 0.54917041, 0.03633962, 0.16156056, 0.36389857,
       0.23068667, 0.34045757, 0.18659702, 0.39391418, 0.88871391,
       0.00291634, 0.55046496, 0.18026766, 0.15636993, 0.27222189,
       0.71679702, 0.17874616, 0.77636652])

In [32]:
np.random.randn(12)

array([-0.65198414,  0.75804692,  1.76851342, -0.51912246,  0.93281173,
       -0.0208892 , -0.70109404, -0.19739203, -0.2846141 , -2.33034579,
        0.30840347,  0.65067642])

In [33]:
np.random.randint(3, 27, 10)

array([ 5, 20, 19,  6, 13, 19, 10, 21, 16, 18])

### se você limitar muito o intervalo, ele repete valores, como abaixo:

In [34]:
np.random.randint(3, 4, 6)

array([3, 3, 3, 3, 3, 3])

# Os atributos mais importantes de um objeto array são:

## ndarray.ndim
 - Nos dá o número de eixos (dimensões) da matriz.
 
## ndarray.shape
- Dá as dimensões da matriz. Esta é uma tupla de inteiros indicando o tamanho da matriz em cada dimensão. Para
  matriz com n linhas em colunas, a forma será (n, m). O comprimento da tupla de forma é, portanto, o número
  de dimensões, ndim.
  
## ndarray.size
 - nos dá o número total de elementos da matriz. 
 
## ndarray.dtype
 - um objeto que descreve o tipo dos elementos na matriz. Pode-se criar ou especificar dtype's usando o tipo padrão do Python.    Além disso, o NumPy fornece seus próprios tipos. (numpy.int32, numpy.int16 e numpy.float64) são alguns exemplos.
 
## ndarray.itemsize
 - Nos dá o tamanho em bytes de cada elemento da matriz. Por exemplo, uma matriz de elementos do tipo float64 tem itemsize
   8 (= 64/8), enquanto um do tipo complex32 tem tamanho de item 4 (= 32/8). 
   
## ndarray.data
 - Nos dá o buffer que contém os elementos reais da matriz. Normalmente, não precisamos usar este atributo porque nós podemos 
   acessará os elementos em uma matriz usando recursos de indexação.

In [35]:
# Dado o Array:
vetor = np.array([1, 2, 3, 4, 5, 6, 7, 9])

In [36]:
print(f'Meu número de eixos é: {vetor.ndim}')
print(f'Meu número de dimensões é: {vetor.shape}')
print(f'Meu número de elementos é: {vetor.size}')
print(f'Eu possuo o seguinte tipo de dados: {vetor.dtype}')
print(f'O tamanho em bytes de cada elemento vetor é: {vetor.itemsize}')
print(f'O buffer que contém os elementos reais da matriz é: {vetor.data}')




Meu número de eixos é: 1
Meu número de dimensões é: (8,)
Meu número de elementos é: 8
Eu possuo o seguinte tipo de dados: int32
O tamanho em bytes de cada elemento vetor é: 4
O buffer que contém os elementos reais da matriz é: <memory at 0x00000209DDFB7888>


## Criação de algumas matrizes especiais:
### Matriz com todos os elementos contendo "0"
### Matriz com todos os elementos contendo "1"
### Matriz Identidade
### Matriz diagonal

In [41]:
matriz_0 = np.zeros((4, 5))
print(matriz_0)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [40]:
matriz_1 = np.ones((4, 5))
print(matriz_1)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [45]:
matriz_identidade = np.eye(4)
print(matriz_identidade)
# Sempre uma madriz quadrada


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [47]:
matriz_diag = np.diag([4, 5, 1, 6])
print(matriz_diag)
# Sempre uma madriz quadrada, a dimensão vai depender da quantidade de elementos da diagonal passada.

[[4 0 0 0]
 [0 5 0 0]
 [0 0 1 0]
 [0 0 0 6]]


# Criando um Array com mais de uma dimensão 

In [10]:
b = np.array([[1, 2, 3], [1, 4, 9]])

In [11]:
print(b)

[[1 2 3]
 [1 4 9]]


In [ ]:
# Note que a quantidade de "colchetes" que finaliza o Array, mostra quantas dimensões ele possui.