# O que é Numpy

###  Numpy é um pacote para computação científica usado em Python, que fornece recursos e uma variedade de rotinas para operações rápidas em matrizes, incluindo matemática, lógica, manipulação de formas, classificação, seleção, E/S (I/O), transformações discretas de Fourier, álgebra linear básica, operações estatísticas básicas, simulação aleatória e muito mais.


## Criação de um Array:

### 1) A biblioteca Numpy não é nativa, logo temos que importá-la;
### 2) É comum na comunidade Python você dá um elias para a biblioteca, usaremos a padrão "np";
### 3) Guardamos o Array em uma variável.

In [1]:
import numpy as np

## Criando um Array unidimensional 

In [2]:
a = np.array([1, 2, 3])

In [3]:
# observemos o tipo do objeto criado
print(type(a)) 
print(a)

<class 'numpy.ndarray'>
[1 2 3]


## Criando um Array com a função ( arange() )
- A função arange cria um arranjo contendo uma seqüência de valores especificados em um intervalo com início e fim dados, espaçados de maneira uniforme.

### np.arange(2, 15, 3, dtype=float)
- 2 = ponto de partida
- 15 = ponto de parada
- 3 = incremento
- dtype=float = tpipo de dado

In [4]:
np.arange(1, 10, 2, dtype=float)

array([1., 3., 5., 7., 9.])

## Criando um Array com o método ( linspace() )
-  A função linspace cria uma seqüência de números uniformemente espaçados entre os limites dados.

### np.linspace(1.0, 10.0, num = 5, dtype=float)
- 1.0 = ponto de partida
- 10.0 = ponto de parada
- 5 = quantidade de valores
- dtype=float = tipo de dado

In [5]:
np.linspace(1, 10, num=7, dtype=float)

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

## Criando um Array com:
### rand
- Cria um array com distribuição uniforme de números aleatórios entre 0 e 1.
 - np.random.rand(10)
   - 10 = número de valores.
   
### randn
- Cria um array de distribuição normal, de média 0 e variância 1.
 - np.random.randn(10)
   - 10 = número de valores.


### randint
- Cria um array com o número determinado de valores inteiros, aleatórios em um intervalo estabelecido. 
 - np.random.randint(5, 20, 12)
   - 5 = início 
   - 20 = final 
   - 12 = quantidade de valores

In [10]:
np.random.rand(23)      

array([0.83142724, 0.54364796, 0.31834   , 0.81551447, 0.21008779,
       0.98227052, 0.81535052, 0.77066535, 0.55808399, 0.51455287,
       0.45852474, 0.29464199, 0.61853925, 0.93949436, 0.4552601 ,
       0.18658242, 0.36562028, 0.28579802, 0.2527317 , 0.5997818 ,
       0.3073718 , 0.65478574, 0.17317511])

In [11]:
np.random.randn(12)

array([-0.1478466 ,  1.20622335, -0.59236953, -1.37509721, -0.22070083,
        0.6797781 ,  0.81060657, -0.49687069,  0.29952694, -2.20629175,
       -1.18506427, -0.95595904])

In [12]:
np.random.randint(3, 27, 10)

array([13, 19, 11, 21, 19, 23,  3, 12, 25, 10])

### se você limitar muito o intervalo, ele repete valores, como abaixo:

In [13]:
np.random.randint(3, 4, 6)

array([3, 3, 3, 3, 3, 3])

## Criando um Array com mais de uma dimensão 

In [6]:
b = np.array([[1, 2, 3], [1, 4, 9]])

In [7]:
print(b)

[[1 2 3]
 [1 4 9]]


# Os atributos mais importantes de um objeto array são:

## ndarray.ndim
 - Nos dá o número de eixos (dimensões) da matriz.
 
## ndarray.shape
- Dá as dimensões da matriz. Esta é uma tupla de inteiros indicando o tamanho da matriz em cada dimensão. Para
  matriz com n linhas em colunas, a forma será (n, m). O comprimento da tupla de forma é, portanto, o número
  de dimensões, ndim.
  
## ndarray.size
 - nos dá o número total de elementos da matriz. 
 
## ndarray.dtype
 - um objeto que descreve o tipo dos elementos na matriz. Pode-se criar ou especificar dtype's usando o tipo padrão do Python.    Além disso, o NumPy fornece seus próprios tipos. (numpy.int32, numpy.int16 e numpy.float64) são alguns exemplos.
 
## ndarray.itemsize
 - Nos dá o tamanho em bytes de cada elemento da matriz. Por exemplo, uma matriz de elementos do tipo float64 tem itemsize
   8 (= 64/8), enquanto um do tipo complex32 tem tamanho de item 4 (= 32/8). 
   
## ndarray.data
 - Nos dá o buffer que contém os elementos reais da matriz. Normalmente, não precisamos usar este atributo porque nós podemos 
   acessará os elementos em uma matriz usando recursos de indexação.